Disable Java code generation
SpineEventEngine/bootstrap pull request #14
Opened 2019-04-19 15:42 UTC by dmdashenkov

This PR introduces the opportunity for the plugin users to disable Java code generation in Java modules.

In order to do that, apply the following config:
```gradle
spine.enableJava().withoutCodeGeneration()
```

2019-04-19 15:57 UTC, dmdashenkov commented
@armiol, PTAL.

2019-04-22 13:54 UTC, dmdashenkov commented
@armiol, PTAL.

2019-04-22 14:12 UTC, armiol requested changes
@dmdashenkov please see my comments.

2019-04-22 14:12 UTC, armiol commented on README.md
> +spine.enableJava().withoutCodeGeneration()
Is this up-to-date?

2019-04-22 14:20 UTC, armiol approved these changes

2019-04-30 13:25 UTC, merged