Configure gRPC generation
SpineEventEngine/bootstrap pull request #4
Opened 2019-03-19 16:50 UTC by dmdashenkov

2019-03-21 12:51 UTC, dmdashenkov commented
@alexander-yevsyukov, PTAL.

2019-03-21 14:45 UTC, alexander-yevsyukov requested changes
Please see my comments.

2019-03-21 14:45 UTC, alexander-yevsyukov commented on plugin/src/main/java/io/spine/tools/bootstrap/CodeGenExtension.java
> +        ProtobufGenerator getProtobufGenerator() {
Why do we need `get` prefixes here?

2019-03-21 14:45 UTC, alexander-yevsyukov commented on plugin/src/main/java/io/spine/tools/bootstrap/CodeGenExtension.java
> +        ProtobufGenerator getProtobufGenerator() {
The `set` prefix in builders look reasonable to me. But we can do without `get` in handcrafted builder classes.

2019-03-21 14:45 UTC, alexander-yevsyukov commented on plugin/src/main/java/io/spine/tools/bootstrap/CodeLayout.java
> +public interface CodeLayout {
This name looks like a code formatting thing. Why isn't it `SourceSet`, for example?

2019-03-21 14:45 UTC, alexander-yevsyukov commented on plugin/src/main/java/io/spine/tools/bootstrap/CodeLayout.java
> +     * <p>The directory should have a sub-directory for each source set present in the project.
> The directory should have a sub-directory...

... then it's probably not `Path` but rather a custom class or interface, which reflects the fact that it has three sub-directories.

2019-03-21 14:45 UTC, alexander-yevsyukov commented on plugin/src/main/java/io/spine/tools/bootstrap/DependencyTarget.java
> +     * <p>Though {@code compile} configuration is deprecated in Gradle, it is still used in order to
What do we do when Gradle removes it?

2019-03-21 14:45 UTC, alexander-yevsyukov commented on plugin/src/main/java/io/spine/tools/bootstrap/DependencyTarget.java
> +    default void compile(String notation) {
The `notation` parameter needs description. Or, put the `depend(String, String)` method before those that refer to it in the `@see` clause.

2019-03-21 14:45 UTC, alexander-yevsyukov commented on plugin/src/main/java/io/spine/tools/bootstrap/Ext.java
> +    private static final String GRPC = "grpc";
Can we transform the `Property` class into enum, having `grpc`, `protoc`, `build` etc. as its members?

2019-03-21 14:45 UTC, alexander-yevsyukov commented on plugin/src/main/java/io/spine/tools/bootstrap/Ext.java
> +    private static final class Property {
This functionality looks like a useful thing not only for bootstrapping. It is reusable enough for working with Gradle model for other things.

2019-03-21 14:45 UTC, alexander-yevsyukov commented on plugin/src/main/java/io/spine/tools/bootstrap/JavaExtension.java
>  package io.spine.tools.bootstrap;
I think the package should be either `io.spine.tools.gradle.bootstrap` (under `gradle`) or `io.spine.tools.gradle` (assuming the reusability) with a small fraction of code residing under `gradle.bootstrap` for the very purpose of bootstrapping.

2019-03-21 14:45 UTC, alexander-yevsyukov commented on plugin/src/main/java/io/spine/tools/bootstrap/protobuf/ProtocPlugin.java
> +package io.spine.tools.bootstrap.protobuf;
How about `io.spine.tools.protoc` package for this?

2019-03-21 17:26 UTC, dmdashenkov commented
@alexander-yevsyukov, PTAL again.

2019-03-21 17:36 UTC, alexander-yevsyukov requested changes
Please see my comments.

2019-03-21 17:36 UTC, alexander-yevsyukov commented on plugin/src/main/java/io/spine/tools/gradle/SourceLayout.java
> +public interface SourceLayout {
How about `DirectoryStructure` or something like this?

2019-03-22 13:23 UTC, dmdashenkov commented
@alexander-yevsyukov, PTAL.

2019-03-22 14:47 UTC, alexander-yevsyukov approved these changes
LGTM

2019-03-22 14:47 UTC, merged