Configure dependency exclusions
SpineEventEngine/bootstrap pull request #8
Opened 2019-04-08 12:51 UTC by dmdashenkov

Previously, Spine users had to exclude certain transitive dependencies from their runtime classpath manually. This was required due to runtime collisions in the Protobuf class definitions.

The configuration is non-intuitive and ad-hock-ish:
```gradle
configurations {
    runtimeClasspath.exclude group 'com.google.protobuf', name: 'protobuf-lite'
    testRuntimeClasspath.exclude group 'com.google.protobuf', name: 'protobuf-lite'
}
```

This PR enables the Bootstrap plugin to perform this configuration automatically for all Java projects.

2019-04-08 14:31 UTC, dmdashenkov commented
@armiol, PTAL.

2019-04-09 11:01 UTC, dmdashenkov commented
@armiol, PTAL again.

2019-04-09 17:46 UTC, armiol requested changes
@dmdashenkov mostly LGTM. Please see my comments.

2019-04-09 17:46 UTC, armiol commented on plugin/src/main/java/io/spine/tools/gradle/Dependency.java
> +     * Obtains the module group ID.
It's not module anymore. Please update through the changeset.

2019-04-09 17:46 UTC, armiol commented on plugin/src/main/java/io/spine/tools/gradle/ProjectDependencyTarget.java
> +                "group", module.groupId(),
I think the literals used here deserve to be documented. Please have a Javadoc for this method.

2019-04-10 10:05 UTC, dmdashenkov commented
@armiol, PTAL.

2019-04-10 11:42 UTC, armiol approved these changes

2019-04-10 11:46 UTC, merged